# Generated by Django 3.2.24 on 2024-05-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEEGV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipgrade_option',
            name='vipgo_score',
            field=models.IntegerField(default=8000),
            preserve_default=False,
        ),
    ]
