# Generated by Django 3.2.24 on 2024-05-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEEGV', '0002_vipgrade_option_vipgo_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipbenifitothermanager',
            name='vipbo_number',
            field=models.CharField(max_length=40, null=True, verbose_name='수량'),
        ),
    ]
