# Generated by Django 3.2.24 on 2025-01-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SEEGV', '0003_alter_vipbenifitothermanager_vipbo_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='gs_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SEEGV.giftconstate'),
        ),
        migrations.AlterField(
            model_name='giftcon',
            name='gc_categoryNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vipclient',
            name='vipg_title',
            field=models.CharField(max_length=150, verbose_name='제목'),
        ),
    ]
